### ISSUE TITLE
How long does it last?

### ISSUE THREAD

**Issue by AvaQueen-Official** [developeranaz/cloudshell-novnc-automation#1]
Is it 24/7/365?

**Comment by developeranaz** [comment]
It's not permanent, and you can't use Cloudshell for free 24/7.
Free Cloudshell has its own limitations. It does not have a permanent public IP address unlike other paid services.
The free ngrok and cloudshell service does not last long, and the connection will be disconnected after 1 hour.

I tried 6 hours max by creating a VM from a google account in your device and logging into the same google account inside the VM's Firefox browser and it stayed in the cloudshell session.
