### ISSUE TITLE
can it run 24/7?

### ISSUE THREAD

**Issue by AvaQueen-Official** [developeranaz/cloudshell-novnc-automation#2]

**Comment by developeranaz** [comment]
No its not permanent

**Comment by AvaQueen-Official** [comment]
how long is the maximum?

**Comment by developeranaz** [comment]
> how long is the maximum?

maximum 6 hours

**Comment by AvaQueen-Official** [comment]
@developeranaz why is that? Is there any way to possibly bypass?

**Comment by developeranaz** [comment]
> @developeranaz why is that? Is there any way to possibly bypass?

Unfortunately, I don't know anything to bypass free Cloudshell 🙂
